CREATE TABLE FORMA_PAGAMENTO_17 (
  A17_id INTEGER   NOT NULL ,
  A17_descricao VARCHAR(255)   NOT NULL ,
  A17_nome VARCHAR(255)   NOT NULL ,
  A17_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A17_id));




CREATE TABLE FILIAL_20 (
  A20_id INTEGER   NOT NULL ,
  A20_nome VARCHAR(255)   NOT NULL ,
  A20_gerente VARCHAR(255)   NOT NULL ,
  A20_email VARCHAR(255)    ,
  A20_estado VARCHAR(255)      ,
PRIMARY KEY(A20_id));




CREATE TABLE TRANSPORTADORA_16 (
  A16_id INTEGER   NOT NULL ,
  A16_nome VARCHAR(255)   NOT NULL ,
  A16_email VARCHAR(255)    ,
  A16_cnpj VARCHAR(255)   NOT NULL ,
  A16_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A16_id));




CREATE TABLE FORNECEDOR_10 (
  A10_id INTEGER   NOT NULL ,
  A10_nome VARCHAR(255)   NOT NULL ,
  A10_cnpj VARCHAR(255)   NOT NULL ,
  A10_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A10_id));




CREATE TABLE REGIAO_02 (
  A02_id INTEGER   NOT NULL ,
  A02_nome VARCHAR(255)   NOT NULL ,
  A02_estado VARCHAR(255)   NOT NULL ,
  A02_descricao VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A02_id));




CREATE TABLE PLATAFORMA_15 (
  A15_id INTEGER   NOT NULL ,
  A15_nome VARCHAR(255)   NOT NULL ,
  A15_descricao VARCHAR(255)   NOT NULL ,
  A15_idadeLimite INTEGER   NOT NULL ,
  A15_persona VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A15_id));




CREATE TABLE NOTA_FISCAL_12 (
  A12_id INTEGER   NOT NULL ,
  A12_numero INTEGER   NOT NULL ,
  A12_dataEmissao DATETIME   NOT NULL   ,
PRIMARY KEY(A12_id));




CREATE TABLE DISPOSITIVO_ACESSO_21 (
  A21_id INTEGER   NOT NULL ,
  A21_categoria VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A21_id));




CREATE TABLE CLASSIFICACAO_PRODUTO_18 (
  A18_id INTEGER   NOT NULL ,
  A18_nome VARCHAR(255)   NOT NULL ,
  A18_descricao VARCHAR(255)   NOT NULL ,
  A18_idadeLimite INTEGER   NOT NULL   ,
PRIMARY KEY(A18_id));




CREATE TABLE CARGO_30 (
  A30_id INTEGER   NOT NULL ,
  A30_nome VARCHAR(255)   NOT NULL ,
  A30_setor INTEGER   NOT NULL ,
  A30_oficio VARCHAR(255)   NOT NULL ,
  A30_descricao VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A30_id));




CREATE TABLE CATEGORIA_19 (
  A19_id INTEGER   NOT NULL ,
  A19_nome VARCHAR(255)   NOT NULL ,
  A19_descricao VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A19_id));




CREATE TABLE CLIENTE_01 (
  A01_id INTEGER   NOT NULL ,
  A01_nome VARCHAR(255)   NOT NULL ,
  A01_nomeSocial VARCHAR(255)    ,
  AO1_pronome VARCHAR(255)    ,
  A01_genero VARCHAR(255)    ,
  A01_dataNasc DATE   NOT NULL ,
  A01_estadoCivil VARCHAR(255)   NOT NULL ,
  A01_cpf VARCHAR(255)   NOT NULL ,
  A01_email VARCHAR(255)   NOT NULL ,
  A01_cepOriginal CHAR(11)    ,
  A01_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A01_id));




CREATE TABLE COMISSAO_13 (
  A13_id INTEGER   NOT NULL ,
  A13_porCentagem DOUBLE   NOT NULL   ,
PRIMARY KEY(A13_id));




CREATE TABLE TELEFONE_FILIAL_27 (
  A27_id INTEGER   NOT NULL ,
  A20_id INTEGER   NOT NULL ,
  A27_telefone VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A27_id)  ,
  FOREIGN KEY(A20_id)
    REFERENCES FILIAL_20(A20_id));


CREATE INDEX TELEFONE_FILIAL_27_FKIndex1 ON TELEFONE_FILIAL_27 (A20_id);


CREATE INDEX IFK_Possui ON TELEFONE_FILIAL_27 (A20_id);


CREATE TABLE PARCERIA_08 (
  A08_id INTEGER   NOT NULL ,
  A02_id INTEGER   NOT NULL ,
  A08_nome VARCHAR(255)   NOT NULL ,
  A08_nacional BOOL   NOT NULL ,
  A08_dataValidade DATE   NOT NULL ,
  AO8_porte  VARCHAR(255)   NOT NULL ,
  A08_descricao VARCHAR(255)    ,
  A08_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A08_id)  ,
  FOREIGN KEY(A02_id)
    REFERENCES REGIAO_02(A02_id));


CREATE INDEX PARCERIA_08_FKIndex1 ON PARCERIA_08 (A02_id);


CREATE INDEX IFK_Reside ON PARCERIA_08 (A02_id);


CREATE TABLE VENDEDOR_14 (
  A14_id INTEGER   NOT NULL ,
  A13_id INTEGER   NOT NULL ,
  A14_cpf VARCHAR(255)   NOT NULL ,
  A14_nome VARCHAR(255)   NOT NULL ,
  A14_dataNasc DATE   NOT NULL ,
  A14_terminoContrato DATE   NOT NULL ,
  A14_email VARCHAR(255)   NOT NULL ,
  A14_codigoDeUso VARCHAR(255)   NOT NULL ,
  A14_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A14_id)  ,
  FOREIGN KEY(A13_id)
    REFERENCES COMISSAO_13(A13_id));


CREATE INDEX VENDEDOR_14_FKIndex1 ON VENDEDOR_14 (A13_id);


CREATE INDEX IFK_Recebe ON VENDEDOR_14 (A13_id);


CREATE TABLE TELEFONE_CLIENTE_07 (
  A07_id INTEGER   NOT NULL ,
  A01_id INTEGER   NOT NULL ,
  A07_numero VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A07_id)  ,
  FOREIGN KEY(A01_id)
    REFERENCES CLIENTE_01(A01_id));


CREATE INDEX TELEFONE_07_FKIndex1 ON TELEFONE_CLIENTE_07 (A01_id);


CREATE INDEX IFK_Possui ON TELEFONE_CLIENTE_07 (A01_id);


CREATE TABLE CLASSIFICACAO_CLIENTE_31 (
  A31_id INTEGER   NOT NULL ,
  A01_id INTEGER   NOT NULL ,
  A31_categoria VARCHAR(255)   NOT NULL ,
  A31_renda INTEGER      ,
PRIMARY KEY(A31_id)  ,
  FOREIGN KEY(A01_id)
    REFERENCES CLIENTE_01(A01_id));


CREATE INDEX CLASSIFICACAO_CLIENTE_31_FKIndex1 ON CLASSIFICACAO_CLIENTE_31 (A01_id);


CREATE INDEX IFK_Tem ON CLASSIFICACAO_CLIENTE_31 (A01_id);


CREATE TABLE TELEFONE_VENDEDOR_26 (
  A26_id INTEGER   NOT NULL ,
  A14_id INTEGER   NOT NULL ,
  A26_telefone VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A26_id)  ,
  FOREIGN KEY(A14_id)
    REFERENCES VENDEDOR_14(A14_id));


CREATE INDEX TELEFONE_VENDEDOR-26_FKIndex1 ON TELEFONE_VENDEDOR_26 (A14_id);


CREATE INDEX IFK_Possui ON TELEFONE_VENDEDOR_26 (A14_id);


CREATE TABLE TELEFONE_PARCEIRA_25 (
  A25_id INTEGER   NOT NULL ,
  A08_id INTEGER   NOT NULL ,
  A25_telefone VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A25_id)  ,
  FOREIGN KEY(A08_id)
    REFERENCES PARCERIA_08(A08_id));


CREATE INDEX TELEFONE_PARCEIRA_25_FKIndex1 ON TELEFONE_PARCEIRA_25 (A08_id);


CREATE INDEX IFK_Possui ON TELEFONE_PARCEIRA_25 (A08_id);


CREATE TABLE TELEFONE_TRANSPORTADORA_24 (
  A24_id INTEGER   NOT NULL ,
  A16_id INTEGER   NOT NULL ,
  A24_telefone VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A24_id)  ,
  FOREIGN KEY(A16_id)
    REFERENCES TRANSPORTADORA_16(A16_id));


CREATE INDEX TELEFONE_TRANSPORTADORA_24_FKIndex1 ON TELEFONE_TRANSPORTADORA_24 (A16_id);


CREATE INDEX IFK_Possui ON TELEFONE_TRANSPORTADORA_24 (A16_id);


CREATE TABLE FUNCIONARIO_29 (
  A29_id INTEGER   NOT NULL ,
  A30_id INTEGER   NOT NULL ,
  A29_nome VARCHAR(255)   NOT NULL ,
  A29_nomeSocial VARCHAR(255)   NOT NULL ,
  A29_cpf VARCHAR(255)   NOT NULL ,
  A29_pcd BOOL   NOT NULL ,
  A29_etinia VARCHAR(255)    ,
  A29_genero VARCHAR(255)    ,
  A29_identidade VARCHAR(255)    ,
  A29_pronome VARCHAR(255)    ,
  A29_dataNasc DATE   NOT NULL ,
  A29_dataInicioContrato DATE   NOT NULL ,
  A29_dataFinalContrato DATE    ,
  A29_salario INTEGER   NOT NULL ,
  A29_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A29_id)  ,
  FOREIGN KEY(A30_id)
    REFERENCES CARGO_30(A30_id));


CREATE INDEX FUNCIONARIO_29_FKIndex1 ON FUNCIONARIO_29 (A30_id);


CREATE INDEX IFK_Possui ON FUNCIONARIO_29 (A30_id);


CREATE TABLE ENDERECO_EMERGENCIAL_32 (
  A32_id INTEGER   NOT NULL ,
  A02_id INTEGER   NOT NULL ,
  A01_id INTEGER   NOT NULL ,
  A32_bairro VARCHAR(255)   NOT NULL ,
  A32_rua VARCHAR(255)    ,
  A32_numero INTEGER    ,
  A32_complemento VARCHAR(255)      ,
PRIMARY KEY(A32_id)    ,
  FOREIGN KEY(A01_id)
    REFERENCES CLIENTE_01(A01_id),
  FOREIGN KEY(A02_id)
    REFERENCES REGIAO_02(A02_id));


CREATE INDEX ENDERECO_EMERGENCIAL_32_FKIndex1 ON ENDERECO_EMERGENCIAL_32 (A01_id);
CREATE INDEX ENDERECO_EMERGENCIAL_32_FKIndex2 ON ENDERECO_EMERGENCIAL_32 (A02_id);


CREATE INDEX IFK_Tem ON ENDERECO_EMERGENCIAL_32 (A01_id);
CREATE INDEX IFK_Possui ON ENDERECO_EMERGENCIAL_32 (A02_id);


CREATE TABLE CAIXA_11 (
  A11_id INTEGER   NOT NULL ,
  A20_id INTEGER   NOT NULL ,
  A29_id INTEGER   NOT NULL ,
  A11_numeroCaixa CHAR(40)   NOT NULL ,
  A11_preferencial BOOL    ,
  A11_rapido BOOL      ,
PRIMARY KEY(A11_id)    ,
  FOREIGN KEY(A29_id)
    REFERENCES FUNCIONARIO_29(A29_id),
  FOREIGN KEY(A20_id)
    REFERENCES FILIAL_20(A20_id));


CREATE INDEX CAIXA_11_FKIndex1 ON CAIXA_11 (A29_id);
CREATE INDEX CAIXA_11_FKIndex2 ON CAIXA_11 (A20_id);


CREATE INDEX IFK_Tem ON CAIXA_11 (A29_id);
CREATE INDEX IFK_Possui ON CAIXA_11 (A20_id);


CREATE TABLE PRODUTO_04 (
  A04_id INTEGER   NOT NULL ,
  A19_id INTEGER   NOT NULL ,
  A18_id INTEGER   NOT NULL ,
  A04_descricao VARCHAR(255)   NOT NULL ,
  A04_valorUni DOUBLE   NOT NULL   ,
PRIMARY KEY(A04_id)    ,
  FOREIGN KEY(A18_id)
    REFERENCES CLASSIFICACAO_PRODUTO_18(A18_id),
  FOREIGN KEY(A19_id)
    REFERENCES CATEGORIA_19(A19_id));


CREATE INDEX PRODUTO_04_FKIndex1 ON PRODUTO_04 (A18_id);
CREATE INDEX PRODUTO_04_FKIndex2 ON PRODUTO_04 (A19_id);


CREATE INDEX IFK_Possui_Classificacao ON PRODUTO_04 (A18_id);
CREATE INDEX IFK_Possui_Categoria ON PRODUTO_04 (A19_id);


CREATE TABLE PLATAFORMA_DO_VENDEDOR_28 (
  A14_id INTEGER   NOT NULL ,
  A15_id INTEGER   NOT NULL   ,
PRIMARY KEY(A14_id, A15_id)    ,
  FOREIGN KEY(A14_id)
    REFERENCES VENDEDOR_14(A14_id),
  FOREIGN KEY(A15_id)
    REFERENCES PLATAFORMA_15(A15_id));


CREATE INDEX VENDEDOR_14_has_PLATAFORMA_15_FKIndex1 ON PLATAFORMA_DO_VENDEDOR_28 (A14_id);
CREATE INDEX VENDEDOR_14_has_PLATAFORMA_15_FKIndex2 ON PLATAFORMA_DO_VENDEDOR_28 (A15_id);


CREATE INDEX IFK_Utiliza_Vendedor ON PLATAFORMA_DO_VENDEDOR_28 (A14_id);
CREATE INDEX IFK_Utiliza_Plataforma ON PLATAFORMA_DO_VENDEDOR_28 (A15_id);


CREATE TABLE LOTE_PRODUTO_23 (
  A23_id INTEGER   NOT NULL ,
  A10_id INTEGER   NOT NULL ,
  A04_id INTEGER   NOT NULL ,
  A12_id INTEGER   NOT NULL ,
  A23_quantidade INTEGER   NOT NULL ,
  A23_valorUni DOUBLE   NOT NULL ,
  A23_data DATETIME   NOT NULL ,
  A23_dataValidade DATETIME   NOT NULL   ,
PRIMARY KEY(A23_id)      ,
  FOREIGN KEY(A10_id)
    REFERENCES FORNECEDOR_10(A10_id),
  FOREIGN KEY(A04_id)
    REFERENCES PRODUTO_04(A04_id),
  FOREIGN KEY(A12_id)
    REFERENCES NOTA_FISCAL_12(A12_id));


CREATE INDEX LOTE_PRODUTO_23_FKIndex1 ON LOTE_PRODUTO_23 (A10_id);
CREATE INDEX LOTE_PRODUTO_23_FKIndex2 ON LOTE_PRODUTO_23 (A04_id);
CREATE INDEX LOTE_PRODUTO_23_FKIndex3 ON LOTE_PRODUTO_23 (A12_id);


CREATE INDEX IFK_Fornece_Fornecedor ON LOTE_PRODUTO_23 (A10_id);
CREATE INDEX IFK_Fornece_Produto ON LOTE_PRODUTO_23 (A04_id);
CREATE INDEX IFK_Gera_Nota ON LOTE_PRODUTO_23 (A12_id);


CREATE TABLE PEDIDO_03 (
  A03_id INTEGER   NOT NULL ,
  A21_id INTEGER   NOT NULL ,
  A12_id INTEGER   NOT NULL ,
  A16_id INTEGER   NOT NULL ,
  A17_id INTEGER   NOT NULL ,
  A01_id INTEGER   NOT NULL ,
  A03_data DATETIME   NOT NULL ,
  A03_valorTotal DOUBLE   NOT NULL ,
  A03_estado VARCHAR(255)   NOT NULL   ,
PRIMARY KEY(A03_id)          ,
  FOREIGN KEY(A01_id)
    REFERENCES CLIENTE_01(A01_id),
  FOREIGN KEY(A17_id)
    REFERENCES FORMA_PAGAMENTO_17(A17_id),
  FOREIGN KEY(A16_id)
    REFERENCES TRANSPORTADORA_16(A16_id),
  FOREIGN KEY(A12_id)
    REFERENCES NOTA_FISCAL_12(A12_id),
  FOREIGN KEY(A21_id)
    REFERENCES DISPOSITIVO_ACESSO_21(A21_id));


CREATE INDEX PEDIDO_03_FKIndex1 ON PEDIDO_03 (A01_id);
CREATE INDEX PEDIDO_03_FKIndex2 ON PEDIDO_03 (A17_id);
CREATE INDEX PEDIDO_03_FKIndex3 ON PEDIDO_03 (A16_id);
CREATE INDEX PEDIDO_03_FKIndex4 ON PEDIDO_03 (A12_id);
CREATE INDEX PEDIDO_03_FKIndex5 ON PEDIDO_03 (A21_id);


CREATE INDEX IFK_Faz ON PEDIDO_03 (A01_id);
CREATE INDEX IFK_Paga ON PEDIDO_03 (A17_id);
CREATE INDEX IFK_Transporta ON PEDIDO_03 (A16_id);
CREATE INDEX IFK_Gera ON PEDIDO_03 (A12_id);
CREATE INDEX IFK_Possibilita ON PEDIDO_03 (A21_id);


CREATE TABLE ENDERECO_06 (
  A06_id INTEGER   NOT NULL ,
  A10_id INTEGER    ,
  A16_id INTEGER    ,
  A08_id INTEGER    ,
  A20_id INTEGER    ,
  A02_id INTEGER    ,
  A01_id INTEGER    ,
  A06_CEP VARCHAR(11)    ,
  A06_numero INTEGER    ,
  A06_complemento VARCHAR(255)      ,
PRIMARY KEY(A06_id)            ,
  FOREIGN KEY(A01_id)
    REFERENCES CLIENTE_01(A01_id),
  FOREIGN KEY(A02_id)
    REFERENCES REGIAO_02(A02_id),
  FOREIGN KEY(A20_id)
    REFERENCES FILIAL_20(A20_id),
  FOREIGN KEY(A08_id)
    REFERENCES PARCERIA_08(A08_id),
  FOREIGN KEY(A16_id)
    REFERENCES TRANSPORTADORA_16(A16_id),
  FOREIGN KEY(A10_id)
    REFERENCES FORNECEDOR_10(A10_id));


CREATE INDEX ENDERECO_06_FKIndex1 ON ENDERECO_06 (A01_id);
CREATE INDEX ENDERECO_06_FKIndex2 ON ENDERECO_06 (A02_id);
CREATE INDEX ENDERECO_06_FKIndex3 ON ENDERECO_06 (A20_id);
CREATE INDEX ENDERECO_06_FKIndex4 ON ENDERECO_06 (A08_id);
CREATE INDEX ENDERECO_06_FKIndex5 ON ENDERECO_06 (A16_id);
CREATE INDEX ENDERECO_06_FKIndex6 ON ENDERECO_06 (A10_id);


CREATE INDEX IFK_Tem_Cliente ON ENDERECO_06 (A01_id);
CREATE INDEX IFK_Reside ON ENDERECO_06 (A02_id);
CREATE INDEX IFK_Tem_Filial ON ENDERECO_06 (A20_id);
CREATE INDEX IFK_Tem_Parceria ON ENDERECO_06 (A08_id);
CREATE INDEX IFK_Tem_Transportadora ON ENDERECO_06 (A16_id);
CREATE INDEX IFK_Tem_Fornecedor ON ENDERECO_06 (A10_id);


CREATE TABLE PROMOCAO_09 (
  A09_id INTEGER   NOT NULL ,
  A04_id INTEGER   NOT NULL ,
  A09_porCentagem DOUBLE   NOT NULL ,
  A09_estado VARCHAR(255)   NOT NULL ,
  A09_dataInicio DATETIME   NOT NULL ,
  A09_dataFinal DATETIME   NOT NULL   ,
PRIMARY KEY(A09_id)  ,
  FOREIGN KEY(A04_id)
    REFERENCES PRODUTO_04(A04_id));


CREATE INDEX PROMOCAO_09_FKIndex1 ON PROMOCAO_09 (A04_id);


CREATE INDEX IFK_possui ON PROMOCAO_09 (A04_id);


CREATE TABLE ESTOQUE_05 (
  A05_id INTEGER   NOT NULL ,
  A04_id INTEGER   NOT NULL ,
  A05_quantidade INTEGER   NOT NULL   ,
PRIMARY KEY(A05_id)  ,
  FOREIGN KEY(A04_id)
    REFERENCES PRODUTO_04(A04_id));


CREATE INDEX ESTOQUE_05_FKIndex1 ON ESTOQUE_05 (A04_id);


CREATE INDEX IFK_Compoe ON ESTOQUE_05 (A04_id);


CREATE TABLE ITEM_PEDIDO_22 (
  A03_id INTEGER   NOT NULL ,
  A04_id INTEGER   NOT NULL ,
  A22_quantidade INTEGER   NOT NULL ,
  A22_valorPago DOUBLE   NOT NULL   ,
PRIMARY KEY(A03_id, A04_id)    ,
  FOREIGN KEY(A03_id)
    REFERENCES PEDIDO_03(A03_id),
  FOREIGN KEY(A04_id)
    REFERENCES PRODUTO_04(A04_id));


CREATE INDEX PEDIDO_03_has_PRODUTO_04_FKIndex1 ON ITEM_PEDIDO_22 (A03_id);
CREATE INDEX PEDIDO_03_has_PRODUTO_04_FKIndex2 ON ITEM_PEDIDO_22 (A04_id);


CREATE INDEX IFK_Tem_Pedido ON ITEM_PEDIDO_22 (A03_id);
CREATE INDEX IFK_Tem_Produto ON ITEM_PEDIDO_22 (A04_id);



